version: '3.8'

services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DATABASE=wordpress
    ports:
      - "3306:3306"
    secrets:
      - db-password
    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress:6.5.3
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db-password
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "80:80"
    secrets:
      - db-password
    volumes:
      - wordpress-data:/var/lib/wordpress/html

secrets:
  db-password:
    file: ./password.txt

volumes:
  mysql-data:
  wordpress-data: