name: Full Project Deployment
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ÉTAPE 1 : PRÉPARATION WORDPRESS 
      - name: Kompose & Zip WordPress
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.32.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          cd Wordpress
          # On crée le fichier manquant pour éviter l'erreur FATA
          echo "${{ secrets.MYSQL_ROOT_PASSWORD }}" > password.txt
          mkdir -p BoudjemaDyhia
          ../kompose convert -f docker-compose.yml -o BoudjemaDyhia/
          zip -r ../BoudjemaDyhiaWordpress.zip BoudjemaDyhia/
          cd ..

      # PRÉPARATION PYTHON 
      - name: Test & Zip Python
        run: |
          cd Python
          pip install pytest
          # Utilise le test de vérification de fichiers pour éviter les ModuleNotFound
          pytest tests/ 
          mkdir -p BoudjemaDyhiaPython
          # On copie proprement les fichiers pour éviter l'erreur de boucle infinie
          cp api.py db.py utils.py requirements.txt Dockerfile docker-compose.yml BoudjemaDyhiaPython/
          cp -r tests BoudjemaDyhiaPython/
          zip -r ../BoudjemaDyhiaPython.zip BoudjemaDyhiaPython/
          cd ..

      # REGROUPEMENT
      - name: Final Package
        run: |
          mkdir -p final_upload
          mv BoudjemaDyhiaWordpress.zip BoudjemaDyhiaPython.zip final_upload/

      # DÉPLOIEMENT UNIQUE 
      - name: Déploiement FTP (Zéro Suppression)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./final_upload/
          server-dir: RenduDevopsKube/
          dangerous-clean-slate: false
          state-name: "none"