name: WordPress Kube CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # GÉNÉRATION DES MANIFESTES (CI)
  build-and-convert:
    name: Build & Kompose Conversion
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Wordpress
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.32.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose

      - name: Convertir Docker Compose
        run: |
          mkdir out-k8s
          echo "${{ secrets.MYSQL_ROOT_PASSWORD }}" > password.txt
          kompose convert -f docker-compose.yml -o out-k8s/
          
      - name: Créer le dossier et le ZIP du rendu
        run: |
         
          mkdir -p BoudjemaDyhia
          cp out-k8s/* BoudjemaDyhia/
          mkdir -p deploy_folder
          zip -r deploy_folder/BoudjemaDyhiaWordpress.zip BoudjemaDyhia/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  
        with:
          name: wp-zip-payload
          path: Wordpress/deploy_folder/
  # Déploiement (CD)
  deploy:
    name: Déploiement FTP (OVH)
    needs: build-and-convert
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Télécharger le ZIP
        uses: actions/download-artifact@v4
        with:
          name: wp-zip-payload
          path: ./to-ftp

      - name: Déploiement FTP vers OVH
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./to-ftp/
          server-dir: RenduDevopsKube/
          dangerous-clean-slate: false
          state-name: "none"